---
- name: Setup ssh key for root user
  user:
    name: root
    generate_ssh_key: true

#- name: Gather required facts
#  setup:
#    gather_subset:
#      - '!all'
#      - 'ohai'

- name: Gather required facts
  setup:
    gather_subset:
      - 'all'

#      - 'ohai'


#- name: Re-gather facts
#  action: setup
#  tags:
#    - testhosts
- name: Edit yum.conf to not install docs
  lineinfile:
    path: '/etc/yum.conf'
    state: present
    line: 'tstflags=nodocs'
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" 
  # todo: use ansible_os_family 

- name: Install pcp
  yum:
    name: ['pcp-zeroconf']
    state: present
  retries: 10
  delay: 5

- name: Start pcp services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    state: restarted
  with_items:
   - 'pmcd'
   - 'pmlogger'


- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}" 

# swith must need to change the ansible_host /etc/hosts to another ip then run the switch???
#- name: "switch dhcp to static for default or eth0 interface"
#  nmcli:
#    # inf get from ansible_default_ipv4
#    conn_name: "{{ pubif|default(ansible_default_ipv4.alias) }}"
#    ifname: "{{ pubif|default(ansible_default_ipv4.interface) }}"
#    type: ethernet
#    state: present
#    autoconnect: yes
#    dns4: "114.114.114.114"
#    #ip4: "{{ ansible_default_ipv4.address }}/ {{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }} | ipaddr('prefix') "
#    #ip4: "{{ ansible_default_ipv4.address }}/ {{ net_mask | ipaddr('prefix') }}"
#    ip4: "{{ ansible_default_ipv4.address }}/{{ net_mask | ipaddr('prefix') }}"
#    gw4: "{{ ansible_default_ipv4.gateway }}"
#  tags:
#    - test1
#
#- name: "fix static"
#  shell: nmcli con mod "{{ pubif|default(ansible_default_ipv4.interface) }}" ipv4.method manual
#  tags:
#    - test1


- name: "Configuring eth"
  nmcli:
    conn_name: "eth{{ ansible_loop.index }}"
    ifname: "eth{{ ansible_loop.index }}"
    type: ethernet
    state: present
    autoconnect: yes
    dns4: "114.114.114.114"
    ip4: "{{ ip }}/{{ netprefix }}"
    gw4: "{{ gateway[ansible_loop.index0] }}"
  loop: "{{ ips|regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b')|list }}"
  loop_control:
    loop_var:  ip
    # default is item
    #index_var: idx
    extended: yes
  tags:
    - test

- name: "fix static"
  shell: nmcli con mod "eth{{ ansible_loop.index }}" ipv4.method manual
  loop: "{{ ips|regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b')|list }}"
  loop_control:
    extended: yes
  tags:
    - test

#- name: Re-gather facts
#  action: setup
#  tags:
#    - testhosts
#- debug:
#    var=hostvars

- name: Build hosts file (backups will be made)
  vars:
    glusinf: "ansible_{{ glusterinf }}"
    res: "{{ hostvars[item][glusinf].ipv4.address }}  {{ item }} {{ hostvars[item]['ansible_hostname']}}"
  lineinfile: 
    path=/etc/hosts 
    regexp='.*{{ item }}$' 
    line="{{ hostvars[item][glusinf].ipv4.address }}  {{ item }} {{ hostvars[item]['ansible_hostname']}}"
    state=present 
    backup=yes
  loop: "{{ groups['cluster_machines'] }}"
  #loop: "{{ groups['all'] }}"
  tags:
    - testhosts

- name: set timezone
  timezone:
    name: Asia/Shanghai
  tags:
    - timezone


- name: config repo base exclude 
  #community.general.ini_file:
  ini_file:
    path: /etc/yum.repos.d/CentOS-Base.repo
    section: base
    option: exclude
    value: "glusterfs*"
    mode: '0600'
    backup: yes

- name: config repo base exclude 
  #community.general.ini_file:
  ini_file:
    path: /etc/yum.repos.d/CentOS-Base.repo
    section: updates
    option: exclude
    value: "glusterfs-*"
    mode: '0600'
    backup: yes

# why no impact?
- name: config repo epel exclude 
  ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: epel
    option: exclude
    value: "glusterfs-*"
    mode: '0600'
    backup: yes
