---
- name: Gather required facts
  setup:
    gather_subset:
      - '!all'
      - 'ohai'

- name: Add EPEL repository
  vars:
    config:
      "8": "https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir"
      "7": "https://mirrors.fedoraproject.org/mirrorlist?repo=epel-7&arch=$basearch"
  yum_repository:
    name: epel
    description: EPEL YUM repo
    mirrorlist: "{{ config[ansible_distribution_major_version] }}"
    enabled: yes
    gpgcheck: no
    keepalive: yes
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" 

- name: Install wget
  yum:
    name: [ 'wget' , 'createrepo' ]
    state: present
  retries: 10
  delay: 5

- name: delete the directory
  file:
    path: "{{ tempdir }}"
    state: absent

- name: create the directory
  file:
    path: "{{ tempdir }}"
    state: directory
    mode: '0755'

- name: Download rpms from custom_build_url provided
  shell:
    cmd: wget -P "{{ tempdir }}" -r -nH --cut-dirs=100 --no-parent -A '*'  "{{ custom_build_url }}"
    chdir: "{{ tempdir }}"
  args:
    warn: false
  when: custom_build_url is defined

- name: Copy custom rpms from custom_build_path to remote machine
  copy:
    src: "{{ custom_build_path |  regex_replace('$', '/') }}"
    dest: "{{ tempdir }}"
    owner: root
    group: root
    mode: '0644'
  when: custom_build_path is defined

- name: Create local repository
  shell:
    cmd: createrepo "{{ tempdir }}"

- name: Configure local repo
  yum_repository:
    name: "glusterlocal"
    description: "repository for custom build of glusterfs"
    baseurl: "file://{{ tempdir }}/"
    gpgcheck: false
    repo_gpgcheck: false
    enabled: 1

- name: downloading custom repository from given build_repo_url
  get_url:
    url: "{{ custom_build_repo_url }}"
    dest: /etc/yum.repos.d/CustomGluster.repo
    mode: '0644'
  when: custom_build_repo_url is defined
