---
- name: Install glusterfs-fuse
  yum:
    name: [ 'glusterfs-fuse', 'git' ]
    state: present
  retries: 10
  delay: 5

- name: Install glusterfs-fuse
  yum:
    name: [ 'python3' ]
    state: present
  retries: 10
  delay: 5
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS" 
    - ansible_distribution_major_version == "8"

- name: Install additional packages on master client
  yum:
    name: [ 'sshpass', 'ansible', 'tar' ]
    state: present
  retries: 10
  delay: 5
  when: inventory_hostname == groups['master_client'].0

- name: create a symlink for rsh
  file:
    src: /usr/bin/ssh
    dest: /usr/bin/rsh
    owner: root
    group: root
    state: link
  when: inventory_hostname == groups['master_client'].0
  ignore_errors: yes

- name: create a symlink for python3
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    owner: root
    group: root
    state: link
  ignore_errors: yes
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS" 
    - ansible_distribution_major_version == "8"

- name: distribute the ssh key to the remote hosts
  shell: "/usr/bin/sshpass -p \"{{ remote_machine_password }}\" ssh-copy-id -f -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/{{ ssh_key_filename }}.pub  \"{{ remote_machine_username }}@{{ item }}\""
  register: ssh_copy_id_execution
  with_items:
    - "{{ groups['cluster_machines']}}"
  failed_when: ssh_copy_id_execution.rc != 0
  when: inventory_hostname == groups['master_client'].0
